chore: added task native:standalone-build to generate a native image for the standalone

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -15,8 +15,11 @@
 # specific language governing permissions and limitations
 # under the License.
 #
+
 FROM ubuntu:20.04
 LABEL maintainer="Michele Sciabarra michele@nuvolaris.io, Francesco Timperi Tiberi francesco.timperi@gmail.com"
+ARG TARGETPLATFORM
+
 # configure dpkg && timezone
 ENV TZ=Europe/London
 RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections ;\
@@ -33,10 +36,7 @@ RUN apt-get update && apt-get -y upgrade &&\
     python3 python3-pip gcc g++ make \
     silversearcher-ag
 # install java (amazon corretto) and libs
-RUN wget -O- https://apt.corretto.aws/corretto.key | apt-key add - ;\
-    add-apt-repository 'deb https://apt.corretto.aws stable main' ;\
-    apt-get update && apt-get -y install java-11-amazon-corretto-jdk ;\
-    pip3 install --upgrade pip setuptools six 
+RUN pip3 install --upgrade pip setuptools six 
 # python2 stuff
 RUN ln -sf /usr/bin/python3 /usr/bin/python ;\
     curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py ;\
@@ -45,20 +45,45 @@ RUN ln -sf /usr/bin/python3 /usr/bin/python ;\
 # docker
 RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu bionic stable" > /etc/apt/sources.list.d/docker.list ;\
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor > /usr/share/keyrings/docker-archive-keyring.gpg ;\
-    apt-get update && apt-get -y install docker-ce-cli   
-# bloop and coursier
-#RUN curl -sfLo /usr/bin/cs https://git.io/coursier-cli-"$(uname | tr LD ld)" ;\
-#    chmod +x /usr/bin/cs ;\
-#    cs install bloop --only-prebuilt=true --install-dir /usr/local/bin
-# user
-
+    apt-get update && apt-get -y install docker-ce-cli 
 # protobuf setup
 RUN apt-get -y install protobuf-compiler
+
+# install graalvm
+ENV GRAALVM_HOME=/opt/graalvm
+ENV PATH=$GRAALVM_HOME/bin:$PATH
+ARG GRAALVM_VERSION=22.3.3  https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java11-linux-amd64-22.3.3.tar.gz
+
+RUN echo "TARGETPLATFORM is $TARGETPLATFORM"
+RUN if [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
+      wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-linux-aarch64-$GRAALVM_VERSION.tar.gz -O /tmp/graalvm.tar.gz; \
+    elif [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
+      wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-java11-linux-amd64-$GRAALVM_VERSION.tar.gz -O /tmp/graalvm.tar.gz; \
+    else \
+        echo "Unsupported platform: $TARGETPLATFORM"; \
+        exit 1; \      
+    fi && \
+    # Extract GraalVM
+    mkdir -p $GRAALVM_HOME && \
+    tar -xvzf /tmp/graalvm.tar.gz --strip-components=1 -C $GRAALVM_HOME && \
+    rm /tmp/graalvm.tar.gz && \
+    # Install Native Image
+    gu install native-image && \
+    # Clean up
+    apt-get clean
+
+# Set GraalVM as the default Java
+RUN update-alternatives --install /usr/bin/java java $GRAALVM_HOME/bin/java 1
+RUN update-alternatives --install /usr/bin/javac javac $GRAALVM_HOME/bin/javac 1
+
+# Verify GraalVM and Native Image installation
+RUN java -version
+RUN native-image --version
     
 RUN useradd -m openserverless -s /bin/bash ;\
     echo "openserverless ALL=(ALL:ALL) NOPASSWD: ALL" >>/etc/sudoers
 # node
-RUN curl -sL https://deb.nodesource.com/setup_16.x | bash ;\
+RUN curl -sL https://deb.nodesource.com/setup_22.x | bash ;\
     apt-get install -y nodejs ;\
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee /usr/share/keyrings/yarnkey.gpg >/dev/null ;\
     echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list ;\
